# https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/
apiVersion: v1
kind: LimitRange
metadata:
  name: storagelimits
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 60Gi
    min:
      storage: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
    persistentvolumeclaims: "3"
    requests.storage: "100Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "5"
    pods: "10"
    replicationcontrollers: "0"
    secrets: "10"
    services: "2"
    services.loadbalancers: "0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    requests.nvidia.com/gpu: 0
